### PR TITLE
Prevent bundlers from deleting some code in ExpressionManager

### LINKED ISSUE #2346: ExpressionManager not safe to be minified
This is a general observation I made, that probably causes a lot of glitches and issues with people using either the minified version of lottie-web or run lottie-web through their custom build process (this more than often involves a final minification step, at least for production).

I noticed this issue when I found that for some animations, lottie-web would not execute several parts of the animations I intended it to play any more as soon as I created a production build.
After investigating, I realized this is because these animations that caused issues in production were making heavy use of expressions, some of which failed to execute.

In this particular case, the issue was that the expression inside the animation exported by AE via the bodymovin plugin contained references to local variables of the scope found in https://github.com/airbnb/lottie-web/blob/6a4b94f5030bf6974e63fa17550c7390a0257ebd/player/js/utils/expressions/ExpressionManager.js#L344

For example `thisComp` was referenced in the expression, but the production build went over and decided to rename the declared variable in https://github.com/airbnb/lottie-web/blob/6a4b94f5030bf6974e63fa17550c7390a0257ebd/player/js/utils/expressions/ExpressionManager.js#L365 to something else, thereby making the expression crash and not affect the animation any more in production.

A general approach to fixing this, is to wrap variable declarations inside `eval()`statements.
So in this particular case I would suggest to "hard code" the variable mapping whenever an expression is evaluated.
This can be achieved quite simply by writing a slightly more enhanced `eval()` that also knows about a var mapping. At runtime it then expands and stringifies the values of the var mapping and assigns them to the vars making sure that the expressions are safe to run:

```
function safeEval(expr, varMapping) {
   
  let varDeclarations = "";

   Object.keys(varMapping).forEach(key => {
      varDeclarations += `var ${key} = varMapping.${key};\n`;
   });

  return eval(`(function () { ${varDeclarations}; return ${expr} })()`); // wrapping inside custom scope via function to keep compatibility with pre ES6 Browsers
}

```

In case expressions perform side effects on these variable declarations (from what I see that is not really the case), they can also be recaptured and returned in a similar fashion. But as far as I understand expression should not perform side effects on the declared variables.

Finally we could go and adjust line 365 as follows and move it to line 650 (where it is executed) to ensure the variables are captured properly.

```
var expression_function = saveEval('[function _expression_function(){' + val+';scoped_bm_rt=$bm_rt}' + ']', { toWorld,fromWorld,fromComp,toComp,fromCompToSurface, position, rotation, anchorPoint, scale, thisLayer, thisComp,mask,valueAtTime,velocityAtTime, loopIn, loop_in, loopOut, loop_out, smooth, inPoint, outPoint, name, width, height })[0];

```

If that sounds decent to you, I can prepare a PR.

### PR DESCRIPTION
**Pull request by trevcodesjs**
Attempts to resolve #2346

### CODE REVIEW

**Comment by trevcodesjs** [comment]
@lencioni @bodymovin any chance we can get a new release soon?

**Comment by calinoracation** [comment]
@bodymovin Curious if you would be willing to give this a shot? We've been using a `patch-package` version of it in production successfully now for a few months and it seems to resolve the original linked issue that has tripped up a number of folks.

**Comment by maxarias-io** [comment]
> @bodymovin Curious if you would be willing to give this a shot? We've been using a `patch-package` version of it in production successfully now for a few months and it seems to resolve the original linked issue that has tripped up a number of folks.

Hi, do you have any info you can share how to fix this with `patch-package`? Trying to avoid an `eval` warning with `rollup`. Thanks!

**Comment by calinoracation** [comment]
@maxarias-io I believe @bodymovin rolled this fix into the main repo as part of the move to use rollup for lottie-web. If it's not working as expected post rollout, you should file another issue.

FWIW the bodymovin After Effects plugin also has a checkbox if you have control of generating your lottie assets to convert expressions to keyframes that would also resolve this particular issue.

**Comment by bodymovin** [comment]
Closing the PR since it's been rolled out indeed as part of another effort.
Thanks for the PR anyway! I used the code to fix this.

**Pull request closed without merging**
