### PR TITLE
straight lines now rendered as line type

### LINKED ISSUE #1590: Bodymovin AE Export looks strange on some edges
May somebody help me. I get strange artefacts on the edges when I export this in After Effects. Is there somethin I am missing or doing wrong?

[calibration_finished.json.zip](https://github.com/airbnb/lottie-web/files/3116532/calibration_finished.json.zip)

### LINKED ISSUE #1750: Straight line is drawn as a bezier curve causing rendering glitches
Pull request coming up :)  

Fixes #1590

**Tell us about your environment**
chrome 75.0.3770.100 / firefox 68.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
Created an animation that uses straight lines with s sharp corner, forming a "spike". It's an animation, resulting in a miter path being used in the svg.

**What did you expect to happen?**
The animation was displayed correctly

**What actually happened? Please include as much _relevant_ detail as possible.**
At seemingly random frames, the spike changes direction or flickers away. This happens only in chrome and firefox and not in safari. This is because the browser renderer does not know how to handle a straight bezier curve being joined into a miter join.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://lottiefiles.com/share/GqmSAm at frame 14 in my chrome, other frames in firefox.

Cheers!

### PR DESCRIPTION
**Pull request by ZainlessBrombie**
Previously, all lines were Beziér curves. Straight lines are now recognized and displayed as such, remediating a rendering issue with pointy angles in paths.
Fixes #1750
Fixes #1590

### CODE REVIEW

**Comment by ZainlessBrombie** [comment]
Has been tested with various featured animations

**Comment by bodymovin** [comment]
Hi, thanks for the PR.
I've considered doing this in the past but I'm worried about the performance impact of applying this calculation to all path segments to determine which ones are straight lines.
Specially since the method uses `Math.sqrt` and `Math.abs` and is applied twice per calculation.
I understand that it fixes a specific browser issue that doesn't handle correctly straight bezier curves, but the cost seems too high.
If this is definitely needed, I think I'd rather do it when preprocessing all shapes and only to the ones that don't have interpolations applied to them (since that would open a whole new can of worms)
What do you think?

**Comment by ZainlessBrombie** [comment]
Hey :)
I agree about performance being a concern, too, but this issue seems significant enough to warrant a fix. I suggest I improve the performance of the algorithm, I believe to have found another way that uses neither sqrt nor trigonometry, just give me a day :+1:

**Comment by ZainlessBrombie** [comment]
@bodymovin implemented a new version that just does some multiplication. The new code is faster by a factor of 6 in firefox and a factor of 3.6 in chrome.

**Comment by ZainlessBrombie** [comment]
Whatever :smile:

**Pull request closed without merging**
