### PR TITLE
Fix SSR rendering refs airbnb#440

### PR DESCRIPTION
**Pull request by nadnad**
Based on https://github.com/airbnb/lottie-web/issues/440#issuecomment-338057030

### CODE REVIEW

**Comment by kamilakorzec** [comment]
@alx-andru, @vanholtzatwork:
Guys, if you want to, I've created an npm module based on this fork as a temporary fix to make the transition easier: https://www.npmjs.com/package/ssr-lottie-web. I have the same issue in my project.

Merging this PR would make our life a lot easier, though.

**Comment by vanholtzatwork** [comment]
@kamilakorzec Thanks! I will give this a try.

**Comment by alx-andru** [comment]
Thanks @kamilakorzec I'll check it out as well. Would be nice if there would be at least a response if the PR is something to be considered or if there is an alternative solution already in the works

**Comment by bodymovin** [comment]
Hi sorry about the delay on this.
I'll take a loot a t it this weekend and get back to you.

**Comment by alx-andru** [comment]
@bodymovin that's right. I've seen several frameworks taking the same approach, not quite sure if there's a better approach to it.

**Comment by nadnad** [comment]
Fantastic thank you @bodymovin!

**Comment by alx-andru** [comment]
Yes 🙌 @bodymovin

**Pull request merged**
