### PR TITLE
[Canvas worker] pass own canvas fix

### PR DESCRIPTION
**Pull request by knenkne**
Fix https://github.com/airbnb/lottie-web/issues/2782

### CODE REVIEW

**Comment by RobMeyer** [comment]
I'm not a contributor but for what it's worth, I was trying to switch our implementation over to canvas worker and ended up debugging into this and coming to the same conclusion, before I saw this issue. 

The only thing I wasn't sure about was whether it was expected for the consumer to call transferControlToOffscreen if they choose to provide their own canvas via rendererSettings.canvas. In any case, it seems like lottie should add the canvas to transferedObjects, as is done in this change.

**Comment by knenkne** [comment]
> I'm not a contributor but for what it's worth, I was trying to switch our implementation over to canvas worker and ended up debugging into this and coming to the same conclusion, before I saw this issue.
> 
> The only thing I wasn't sure about was whether it was expected for the consumer to call transferControlToOffscreen if they choose to provide their own canvas via rendererSettings.canvas. In any case, it seems like lottie should add the canvas to transferedObjects, as is done in this change.

Hey! Agree, It'll be more clear to execute `transferControlToOffscreen` method behind the scenes, will see that @bodymovin  will say. 
We've lottie's fork with `Worker` support in production for a long time, I can share it with you if u need it. The problem is to match the updates between original repo and fork constantly, thats why we want it running like clockwork here.

**Comment by bodymovin** [comment]
Hey, thanks for the fix!
I was trying it out and it could be valuable to support both scenarios. Perhaps by checking `canvas instanceof OffscreenCanvas` and if it isn't, replace it.
By the way, no need to modify `player/js/module_worker.js`, it isn't used anymore.

**Comment by knenkne** [comment]
> 

Hey, Hernan!
Yeah, It sounds good to support both cases and not hard to implement. I'll do it tomorrow 👍 
And thanks for the clarification about `player/js/module_worker.js` I'll revert my changes there.

**Comment by knenkne** [comment]
> Hey, thanks for the fix! I was trying it out and it could be valuable to support both scenarios. Perhaps by checking `canvas instanceof OffscreenCanvas` and if it isn't, replace it. What do you think? By the way, no need to modify `player/js/module_worker.js`, it isn't used anymore.

Hey, Hernan!
Yeah, It sounds good to support both cases and not hard to implement. I'll do it tomorrow 👍
And thanks for the clarification about player/js/module_worker.js I'll revert my changes there.

**Comment by knenkne** [comment]
Ok, It's not tomorrow, It's restless night 😄 

Checked these cases:
1. Custom canvas
2. Transferred custom canvas
3. Default canvas (created by lottie)

Works like a charm! 🚀

**Comment by knenkne** [comment]
Ok, It's not tomorrow, It's restless night 😄

Checked these cases:

Custom canvas
Transferred custom canvas
Default canvas (created by lottie)
Works like a charm! 🚀

**Comment by knenkne** [comment]
Ok, It's not tomorrow, It's restless night 😄

Checked these cases:
1. Custom canvas
2. Transferred custom canvas
3. Default canvas (created by lottie)

Works like a charm! 🚀

**Comment by bodymovin** [comment]
Amazing!
thanks

**Pull request merged**
