### PR TITLE
Updates to TypeScript definitions

### PR DESCRIPTION
**Pull request by andrewhosgood**
Added void functions and declaration statement for module export

Some TS linters don't like no return defs or missing export definitions

### CODE REVIEW

**Comment by amritk** [comment]
Is there a workaround while this gets merged?

**Comment by andrewhosgood** [comment]
@amritk I couldn't find any workaround and without separating the types out (which means you would still need to modify this module) and I don't think there is a way to redefine the typings that are bundled in this module.

Happy to be shown a way if anyone knows?

I'm had to revert to using GIFs in my TypeScript project until this is resolved :'(

**Comment by amritk** [comment]
Damn, was hoping there was a flag I could change in tsconfig to allow this.

**Comment by bodymovin** [comment]
I'll review this weekend and merge if everything looks good

**Comment by amritk** [comment]
Whats the good word?

**Pull request merged**
