### PR TITLE
added documentation regarding manipulating attributes

### PR DESCRIPTION
**Pull request by spencer1573**
I spent more time than i wish to admit trying to find a way to alter attributes of a running lottie animation and found that this simple attribute assignment worked. It was not immediately obvious to me so i thought I'd point it out to other people.

### CODE REVIEW

**Comment by bodymovin** [comment]
Hi, thanks for the PR, but it might confuse users specifying the instance of the animation as lottie, since the library global variable is named that way.  
Would you mind changing it to something like `instance`?  
You can also refer to the typescript definition to find all available properties
https://github.com/airbnb/lottie-web/blob/master/index.d.ts

**Comment by spencer1573** [comment]
Sorry i didn't get back to you sooner! do you want it to include all the available types instead of just one? I'd love to, i just didn't want to add to much to the docs.

**Comment by spencer1573** [comment]
Hey so i updated the PR to include instance instead of lottie and created a link for index.d.ts.  I can write out all of the items on the AnimationItem instead of refering to them if you want... but i think the link could be sufficient. @bodymovin

**Comment by spencer1573** [comment]
i'm going to close this just because it doesn't seem that important

**Pull request closed without merging**
