### PR TITLE
Fix unintentional stroke clipping on shapes with large stroke-width 

### PR DESCRIPTION
**Pull request by CurosMJ**
The example image below has an Ellipse, with a very large stroke width, and Lottie clips it because the filter element has x, y and width & height applied to it. Removing those attributes make the filter apply on basically the whole target element, which I think is what we want to do. 

I added a condition because I'm not sure if removing those attributes will break other renderers or filters.

How it looks in AE:
image

How it looks in Lottie, without the fix:
image

With the fix, it looks exactly like how it is shown in AE.

Thanks!

### CODE REVIEW

**Comment by bodymovin** [comment]
Hi, I've been hit in the past with browsers not rendering correctly the filters if these properties are not defined. I wish I had documented which ones they were. I want to give it a try at least on the evergreen browsers. Do you have the .aep of your example?

**Comment by CurosMJ** [comment]
Hello, here's a link with the AEP and the bodymovin export: https://drive.google.com/drive/folders/1aXtRXyzIRsDJ-hRUmMFCrjYklwA2sT20?usp=sharing

**Comment by CurosMJ** [comment]
A codepen example can be seen here: https://codepen.io/jadhavm/pen/MWbmNMw

**Comment by bodymovin** [comment]
thanks! wondering if I can do the same with track matte masks. I'll do some tests

**Pull request merged**
