### PR TITLE
Adding two new functions for getting registeredAnimation(s)

### PR DESCRIPTION
**Pull request by TomHoenderdos**
In our project we use multiple bodymovin animations on one page, to be able to get the AnimationItem object I have added two new getter functions.

### CODE REVIEW

**Comment by bodymovin** [comment]
I like the getRegisteredAnimations idea.
What would be the use case for getRegisteredAnimation?

**Comment by TomHoenderdos** [comment]
In our case that's the only one we would actually use.
It's an edge case where you have the animation element but dont want to do the filtering yourself, so you supply the element and you get the correct AnimationItem back.. 
I can refactor / remove it if you want

**Comment by Jeremy-Knudsen** [comment]
Perhaps getRegisteredAnimation() in my case? I'm trying to figure out how to hook up mouse events on my animations. In my case, I have a lot of animations on a single web page. The page is a bunch of DIV tags with the `data-bm-` attributes contained within each. I have included `data-bm-name` as one of those attributes, but it's not clear how I would reference this when a mouseEvent is fired so that I can watch it's current frame and how listen to the onComplete event.

**Comment by bodymovin** [comment]
I see, let me think how it fits and I'll try to merge it.
Is there a reason why you prefer to instantiate animations with html attributes instead of loading the animation with bodymovin.loadAnimation?
The idea of using html tags was for fast and simple integrations and the loadAnimation method was for more control and having an API to interact with.

**Comment by Jeremy-Knudsen** [comment]
It might not have to be merged provided there's a way for me to do what I'm trying to do. I think my usage of the inline attribute method was more a result of the little documentation I had to go on, specifically in terms of examples related to multiple animations on a single page and event handling. It might be nice to document some case studies since there are multiple ways SVG animation can be used: interactive UI controls, ad banners, games, linear animation, etc.

**Comment by TomHoenderdos** [comment]
What is the status of this PR? Is it possible for you to merge my changes? :D

**Comment by julianebrazil** [comment]
hello, sorry, but I very lay with codes... I did not understand if is possible to register an animation, how do I start? I was able to create one animation, and put in my website, but it will have more animations with mouse events, so there is a way to create it without have to create VAR "element", get element ID, path render, etc, to each element for animation?

**Pull request closed without merging**
